### PR TITLE
(6.3) Refactor robotest configuration - keep upgrade_from releases current.

### PR DESCRIPTION
**Pull request by wadells**
## Description
Ports:
* robotest config refactoring from #1837
* version changes from #1179
* test etcd cert fixes from #1815

Changes of interest specific to this branch:

* `pr_config.sh` is updated for 6.3.x
* run.sh no longer attempts authentication before downloading from  https://get.gravitational.io:443
* `version.sh` changes are included because without this 6.3.18 -> 6.3.18-X upgrades are not possible -- which matters now that we try to upgrade from the most recent release.

I removed test.sh and references to it since it [may still be in flux](https://github.com/gravitational/gravity/pull/1837#discussion_r453121148).

## Type of change
* Internal change (not necessarily a bug fix or a new feature)

## Linked tickets and other PRs
* Ports #1837 
* Ports ##1179

## TODOs
- [x] Self-review the change
- [x] Audit automated test run for correctness
- [ ] Address review feedback

## Testing done
See  #1837 for the original testing. For 76.3: the PR Jenkins run should sufficiently exercise the 6.3 PR build relevant changes. We don't care about testing the nightly changes because we don't run nighties on 6.3 so although I made an minor effort to keep this file branch relevant mistakes are moot.

<details><summary><code>make test</code> (to show etcd cert fix)</summary>

```
walt@work:~/git/gravity$ make test
make -C build.assets test
make[1]: Entering directory '/home/walt/git/gravity/build.assets'
docker build \
        --build-arg PROTOC_VER=3.7.1 \
        --build-arg PROTOC_PLATFORM=linux-x86_64 \
        --build-arg GOGO_PROTO_TAG=v1.2.1 \
        --build-arg GRPC_GATEWAY_TAG=v1.8.5 \
        --build-arg VERSION_TAG=0.0.2 \
        --pull --tag gravity-buildbox:latest .
Sending build context to Docker daemon  54.27kB
Step 1/20 : FROM quay.io/gravitational/debian-venti:go1.12.9-stretch
go1.12.9-stretch: Pulling from gravitational/debian-venti
b5b1fde1ae51: Pull complete
b65b451b52af: Pull complete
Digest: sha256:3e0d088ff38afa883683fdc1210763bd2d34a8193f2081d724f8c2a07807bd72
Status: Downloaded newer image for quay.io/gravitational/debian-venti:go1.12.9-stretch
 ---> 7795cd45efba
Step 2/20 : ARG PROTOC_VER
 ---> Running in 75d070b3fe95
Removing intermediate container 75d070b3fe95
 ---> b8f2ab010641
Step 3/20 : ARG PROTOC_PLATFORM
 ---> Running in f38aee9957a7
Removing intermediate container f38aee9957a7
 ---> 3560ac9e6d31
Step 4/20 : ARG GOGO_PROTO_TAG
 ---> Running in 0c11a196faca
Removing intermediate container 0c11a196faca
 ---> bd8267a00948
Step 5/20 : ARG GRPC_GATEWAY_TAG
 ---> Running in 3ca949d9c49d
Removing intermediate container 3ca949d9c49d
 ---> ae98b1336118
Step 6/20 : ARG VERSION_TAG
 ---> Running in a4f41e1ba476
Removing intermediate container a4f41e1ba476
 ---> 5f94b73fee55
Step 7/20 : ENV TARBALL protoc-${PROTOC_VER}-${PROTOC_PLATFORM}.zip
 ---> Running in d711670cf8e9
Removing intermediate container d711670cf8e9
 ---> b13f60817f2c
Step 8/20 : ENV GOGOPROTO_ROOT ${GOPATH}/src/github.com/gogo/protobuf
 ---> Running in 85f54fde2827
Removing intermediate container 85f54fde2827
 ---> d9d4172264f7
Step 9/20 : ENV PROTOC_URL https://github.com/google/protobuf/releases/download/v${PROTOC_VER}/protoc-${PROTOC_VER}-${PROTOC_PLATFORM}.zip
 ---> Running in 6e6c3049db2b
Removing intermediate container 6e6c3049db2b
 ---> 2e55aa990a81
Step 10/20 : RUN adduser jenkins --uid=995 --disabled-password --system
 ---> Running in ebe72065a5c5
Adding system user `jenkins' (UID 995) ...
Adding new user `jenkins' (UID 995) with group `nogroup' ...
Creating home directory `/home/jenkins' ...
Removing intermediate container ebe72065a5c5
 ---> e8d652040244
Step 11/20 : RUN (mkdir -p /gopath/src/github.com/gravitational/gravity &&      chown -R jenkins /gopath &&      mkdir -p /.cache &&      chmod 777 /.cache &&      chmod 777 /tmp)
 ---> Running in 38188de41354
Removing intermediate container 38188de41354
 ---> d0a100b745b9
Step 12/20 : ENV LANGUAGE="en_US.UTF-8"      LANG="en_US.UTF-8"      LC_ALL="en_US.UTF-8"      LC_CTYPE="en_US.UTF-8"      GOPATH="/gopath"      PATH="$PATH:/opt/protoc/bin:/opt/go/bin:/gopath/bin"
 ---> Running in f06f43352d01
Removing intermediate container f06f43352d01
 ---> f2fff3bb016a
Step 13/20 : RUN (mkdir -p /gopath/src/github.com/gravitational &&      cd /gopath/src/github.com/gravitational &&      git clone https://github.com/gravitational/version.git &&      cd /gopath/src/github.com/gravitational/version &&      git checkout ${VERSION_TAG} &&      go install github.com/gravitational/version/cmd/linkflags)
 ---> Running in c6fed4db115d
Cloning into 'version'...
Note: checking out '0.0.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 95d33ec... Merge pull request #5 from gravitational/roman/semver
Removing intermediate container c6fed4db115d
 ---> abd36130963c
Step 14/20 : RUN (mkdir -p /opt/protoc &&      wget --quiet -O /tmp/${TARBALL} ${PROTOC_URL} &&      unzip -d /opt/protoc /tmp/${TARBALL} &&      go get -u github.com/gogo/protobuf/proto github.com/gogo/protobuf/protoc-gen-gogo github.com/gogo/protobuf/gogoproto      github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway      github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger)
 ---> Running in 42efcb67820c
Archive:  /tmp/protoc-3.7.1-linux-x86_64.zip
   creating: /opt/protoc/include/
   creating: /opt/protoc/include/google/
   creating: /opt/protoc/include/google/protobuf/
  inflating: /opt/protoc/include/google/protobuf/wrappers.proto
  inflating: /opt/protoc/include/google/protobuf/field_mask.proto
  inflating: /opt/protoc/include/google/protobuf/api.proto
  inflating: /opt/protoc/include/google/protobuf/struct.proto
  inflating: /opt/protoc/include/google/protobuf/descriptor.proto
  inflating: /opt/protoc/include/google/protobuf/timestamp.proto
   creating: /opt/protoc/include/google/protobuf/compiler/
  inflating: /opt/protoc/include/google/protobuf/compiler/plugin.proto
  inflating: /opt/protoc/include/google/protobuf/empty.proto
  inflating: /opt/protoc/include/google/protobuf/any.proto
  inflating: /opt/protoc/include/google/protobuf/source_context.proto
  inflating: /opt/protoc/include/google/protobuf/type.proto
  inflating: /opt/protoc/include/google/protobuf/duration.proto
   creating: /opt/protoc/bin/
  inflating: /opt/protoc/bin/protoc
  inflating: /opt/protoc/readme.txt
Removing intermediate container 42efcb67820c
 ---> f7d286132766
Step 15/20 : RUN cd ${GOPATH}/src/github.com/gogo/protobuf && git reset --hard ${GOGO_PROTO_TAG} && make install
 ---> Running in 890db1951548
HEAD is now at ba06b47c update typecast in varint decoding (#545)
go install ./proto
go install ./gogoproto
go install ./jsonpb
go install ./protoc-gen-gogo
go install ./protoc-gen-gofast
go install ./protoc-gen-gogofast
go install ./protoc-gen-gogofaster
go install ./protoc-gen-gogoslick
go install ./protoc-gen-gostring
go install ./protoc-min-version
go install ./protoc-gen-combo
go install ./gogoreplace
Removing intermediate container 890db1951548
 ---> fd11ff9ffe6b
Step 16/20 : RUN cd ${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway && git reset --hard ${GRPC_GATEWAY_TAG} && go install ./protoc-gen-grpc-gateway
 ---> Running in ae478a81c5b9
HEAD is now at 20f268a Generate changelog for 1.8.5
Removing intermediate container ae478a81c5b9
 ---> 60994f3180cc
Step 17/20 : ENV PROTO_INCLUDE "/usr/local/include":"${GOPATH}/src":"${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis":"${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis":"${GOGOPROTO_ROOT}/protobuf":"${GOGOPROTO_ROOT}/gogoproto"
 ---> Running in 4335abf2ac49
Removing intermediate container 4335abf2ac49
 ---> bca468b3fb6b
Step 18/20 : RUN wget --quiet -O /usr/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 && chmod +x /usr/bin/dep
 ---> Running in 8de95cbd9b2a
Removing intermediate container 8de95cbd9b2a
 ---> 333a87f66496
Step 19/20 : RUN chmod -R a+rw /gopath
 ---> Running in 6880b5a889e5
Removing intermediate container 6880b5a889e5
 ---> 4a418ff7954d
Step 20/20 : VOLUME ["/gopath/src/github.com/gravitational/gravity"]
 ---> Running in 6d4885161b28
Removing intermediate container 6d4885161b28
 ---> 1e6c8b2b937d
Successfully built 1e6c8b2b937d
Successfully tagged gravity-buildbox:latest
make base-etcd
make[2]: Entering directory '/home/walt/git/gravity/build.assets'
if docker ps | grep testetcd0 --quiet; then \
  echo "ETCD is already running"; \
else \
  echo "starting test ETCD instance"; \
  etcd_instance=; \
  if [ "$etcd_instance" != "" ]; then \
    docker rm -v $etcd_instance; \
  fi; \
  docker run --net=host  --name=testetcd0 -d -v /home/walt/git/gravity/assets/certs:/certs quay.io/coreos/etcd:v2.3.7  -name etcd0 -advertise-client-urls https://localhost:2379,https://localhost:4001  -listen-client-urls https://0.0.0.0:2379,https://0.0.0.0:4001  -initial-advertise-peer-urls https://localhost:2380  -listen-peer-urls https://0.0.0.0:2380  -initial-cluster-token etcd-cluster-1  -initial-cluster etcd0=https://localhost:2380  -initial-cluster-state new --cert-file=/certs/etcd1.pem --key-file=/certs/etcd1-key.pem --peer-cert-file=/certs/etcd1.pem --peer-key-file=/certs/etcd1-key.pem --peer-client-cert-auth --peer-trusted-ca-file=/certs/ca.pem -client-cert-auth --trusted-ca-file=/certs/ca.pem  ; \
fi;
starting test ETCD instance
Unable to find image 'quay.io/coreos/etcd:v2.3.7' locally
v2.3.7: Pulling from coreos/etcd
baa54a8d5296: Pull complete
1b7cd7bbed2b: Pull complete
Digest: sha256:797c185fcf07f1fecf228665ebf8cf7f1b2172853e9dfc02d2d718c582c77493
Status: Downloaded newer image for quay.io/coreos/etcd:v2.3.7
3a11b9fb666d45fadab3fbf9e932c1c14910a0f68911f50cb7b38a55c819f4a9
make[2]: Leaving directory '/home/walt/git/gravity/build.assets'
docker run --net=host --rm=true  \
        -v /home/walt/git/gravity/:/gopath/src/github.com/gravitational/gravity \
        -e "GRAVITY_PKG_PATH=github.com/gravitational/gravity" \
        -e "TEST_PACKAGES=github.com/gravitational/gravity/lib/... github.com/gravitational/gravity/tool/..." \
        -t gravity-buildbox:latest \
        dumb-init make -C /gopath/src/github.com/gravitational/gravity/build.assets FLAGS='-cover -race' TEST_ETCD=true TEST_K8S=false test-inside-container
make: Entering directory '/gopath/src/github.com/gravitational/gravity/build.assets'
TEST_ETCD=true TEST_ETCD_CONFIG='{"nodes": ["https://localhost:4001"], "key":"/gravity/test", "tls_key_file": "/gopath/src/github.com/gravitational/gravity/assets/certs/proxy1-key.pem", "tls_cert_file": "/gopath/src/github.com/gravitational/gravity/assets/certs/proxy1.pem", "tls_ca_file": "/gopath/src/github.com/gravitational/gravity/assets/certs/ca.pem"}' TEST_K8S=false go test github.com/gravitational/gravity/lib/... github.com/gravitational/gravity/tool/... -cover -race
ok      github.com/gravitational/gravity/lib/app        1.866s  coverage: 7.9% of statements
?       github.com/gravitational/gravity/lib/app/api    [no test files]
?       github.com/gravitational/gravity/lib/app/client [no test files]
ok      github.com/gravitational/gravity/lib/app/docker 2.368s  coverage: 17.8% of statements
ok      github.com/gravitational/gravity/lib/app/handler        134.387s        coverage: 38.8% of statements
ok      github.com/gravitational/gravity/lib/app/hooks  2.103s  coverage: 6.7% of statements
ok      github.com/gravitational/gravity/lib/app/resources      2.987s  coverage: 57.1% of statements
ok      github.com/gravitational/gravity/lib/app/service        3.742s  coverage: 28.8% of statements
?       github.com/gravitational/gravity/lib/app/service/test   [no test files]
?       github.com/gravitational/gravity/lib/app/suite  [no test files]
ok      github.com/gravitational/gravity/lib/archive    1.136s  coverage: 39.6% of statements
ok      github.com/gravitational/gravity/lib/autoscale/aws      1.825s  coverage: 37.8% of statements
?       github.com/gravitational/gravity/lib/blob       [no test files]
?       github.com/gravitational/gravity/lib/blob/client        [no test files]
ok      github.com/gravitational/gravity/lib/blob/cluster       4.148s  coverage: 67.1% of statements
ok      github.com/gravitational/gravity/lib/blob/fs    1.857s  coverage: 70.1% of statements
ok      github.com/gravitational/gravity/lib/blob/handler       70.453s coverage: 73.0% of statements
?       github.com/gravitational/gravity/lib/blob/suite [no test files]
ok      github.com/gravitational/gravity/lib/builder    2.249s  coverage: 4.8% of statements
ok      github.com/gravitational/gravity/lib/catalog    2.426s  coverage: 18.3% of statements
ok      github.com/gravitational/gravity/lib/checks     1.669s  coverage: 9.1% of statements
?       github.com/gravitational/gravity/lib/checks/autofix     [no test files]
?       github.com/gravitational/gravity/lib/clients    [no test files]
?       github.com/gravitational/gravity/lib/cloudprovider/aws  [no test files]
?       github.com/gravitational/gravity/lib/cloudprovider/aws/service  [no test files]
ok      github.com/gravitational/gravity/lib/cloudprovider/aws/validation       1.075s  coverage: 16.6% of statements
ok      github.com/gravitational/gravity/lib/cloudprovider/gce  1.046s  coverage: 100.0% of statements
?       github.com/gravitational/gravity/lib/compare    [no test files]
?       github.com/gravitational/gravity/lib/constants  [no test files]
?       github.com/gravitational/gravity/lib/defaults   [no test files]
ok      github.com/gravitational/gravity/lib/devicemapper       1.889s  coverage: 28.6% of statements
?       github.com/gravitational/gravity/lib/docker     [no test files]
ok      github.com/gravitational/gravity/lib/expand     3.560s  coverage: 8.3% of statements
?       github.com/gravitational/gravity/lib/expand/phases      [no test files]
?       github.com/gravitational/gravity/lib/fsm        [no test files]
ok      github.com/gravitational/gravity/lib/helm       2.147s  coverage: 3.3% of statements
ok      github.com/gravitational/gravity/lib/httplib    1.653s  coverage: 5.6% of statements
ok      github.com/gravitational/gravity/lib/hub        1.577s  coverage: 71.5% of statements
ok      github.com/gravitational/gravity/lib/install    4.113s  coverage: 18.7% of statements
?       github.com/gravitational/gravity/lib/install/client     [no test files]
?       github.com/gravitational/gravity/lib/install/dispatcher [no test files]
ok      github.com/gravitational/gravity/lib/install/dispatcher/buffered        1.637s  coverage: 93.3% of statements
ok      github.com/gravitational/gravity/lib/install/dispatcher/direct  1.535s  coverage: 100.0% of statements
?       github.com/gravitational/gravity/lib/install/dispatcher/internal/test   [no test files]
?       github.com/gravitational/gravity/lib/install/engine     [no test files]
?       github.com/gravitational/gravity/lib/install/engine/cli [no test files]
?       github.com/gravitational/gravity/lib/install/engine/interactive [no test files]
ok      github.com/gravitational/gravity/lib/install/phases     1.842s  coverage: 2.1% of statements
?       github.com/gravitational/gravity/lib/install/proto      [no test files]
?       github.com/gravitational/gravity/lib/install/server     [no test files]
ok      github.com/gravitational/gravity/lib/kubernetes 1.759s  coverage: 0.0% of statements
ok      github.com/gravitational/gravity/lib/loc        1.039s  coverage: 45.5% of statements
ok      github.com/gravitational/gravity/lib/localenv   1.877s  coverage: 24.0% of statements
?       github.com/gravitational/gravity/lib/log        [no test files]
?       github.com/gravitational/gravity/lib/modules    [no test files]
?       github.com/gravitational/gravity/lib/network/ebtables   [no test files]
ok      github.com/gravitational/gravity/lib/network/validation 1.771s  coverage: 4.2% of statements
?       github.com/gravitational/gravity/lib/network/validation/proto   [no test files]
ok      github.com/gravitational/gravity/lib/ops        1.768s  coverage: 4.1% of statements
?       github.com/gravitational/gravity/lib/ops/events [no test files]
?       github.com/gravitational/gravity/lib/ops/monitoring     [no test files]
?       github.com/gravitational/gravity/lib/ops/opsclient      [no test files]
ok      github.com/gravitational/gravity/lib/ops/opshandler     111.049s        coverage: 30.3% of statements
?       github.com/gravitational/gravity/lib/ops/opsroute       [no test files]
ok      github.com/gravitational/gravity/lib/ops/opsservice     14.981s coverage: 16.1% of statements
ok      github.com/gravitational/gravity/lib/ops/resources      1.723s  coverage: 32.4% of statements
ok      github.com/gravitational/gravity/lib/ops/resources/gravity      3.406s  coverage: 13.9% of statements
?       github.com/gravitational/gravity/lib/ops/suite  [no test files]
?       github.com/gravitational/gravity/lib/pack       [no test files]
?       github.com/gravitational/gravity/lib/pack/encryptedpack [no test files]
ok      github.com/gravitational/gravity/lib/pack/layerpack     1.942s  coverage: 75.0% of statements
ok      github.com/gravitational/gravity/lib/pack/localpack     1.936s  coverage: 61.1% of statements
?       github.com/gravitational/gravity/lib/pack/suite [no test files]
ok      github.com/gravitational/gravity/lib/pack/webpack       93.850s coverage: 72.1% of statements
ok      github.com/gravitational/gravity/lib/process    2.017s  coverage: 5.5% of statements
?       github.com/gravitational/gravity/lib/processconfig      [no test files]
ok      github.com/gravitational/gravity/lib/report     1.688s  coverage: 8.8% of statements
?       github.com/gravitational/gravity/lib/rpc        [no test files]
?       github.com/gravitational/gravity/lib/rpc/client [no test files]
ok      github.com/gravitational/gravity/lib/rpc/inprocess      1.942s  coverage: 85.5% of statements
?       github.com/gravitational/gravity/lib/rpc/proto  [no test files]
ok      github.com/gravitational/gravity/lib/rpc/proxy  1.041s  coverage: 76.5% of statements
ok      github.com/gravitational/gravity/lib/rpc/server 6.828s  coverage: 57.6% of statements
ok      github.com/gravitational/gravity/lib/run        1.015s  coverage: 85.7% of statements
ok      github.com/gravitational/gravity/lib/schema     1.865s  coverage: 23.9% of statements
?       github.com/gravitational/gravity/lib/schema/defaults    [no test files]
?       github.com/gravitational/gravity/lib/schema/unversioned [no test files]
?       github.com/gravitational/gravity/lib/schema/v1  [no test files]
?       github.com/gravitational/gravity/lib/sni        [no test files]
?       github.com/gravitational/gravity/lib/state      [no test files]
?       github.com/gravitational/gravity/lib/status     [no test files]
ok      github.com/gravitational/gravity/lib/storage    3.966s  coverage: 13.2% of statements
ok      github.com/gravitational/gravity/lib/storage/clusterconfig      2.007s  coverage: 52.9% of statements
ok      github.com/gravitational/gravity/lib/storage/keyval     13.414s coverage: 49.8% of statements
?       github.com/gravitational/gravity/lib/storage/suite      [no test files]
ok      github.com/gravitational/gravity/lib/system     1.604s  coverage: 16.4% of statements
?       github.com/gravitational/gravity/lib/system/environ     [no test files]
?       github.com/gravitational/gravity/lib/system/mount       [no test files]
?       github.com/gravitational/gravity/lib/system/service     [no test files]
?       github.com/gravitational/gravity/lib/system/signals     [no test files]
ok      github.com/gravitational/gravity/lib/systeminfo 1.721s  coverage: 11.8% of statements
ok      github.com/gravitational/gravity/lib/systemservice      1.533s  coverage: 9.6% of statements
?       github.com/gravitational/gravity/lib/terraform/provider [no test files]
?       github.com/gravitational/gravity/lib/testutils  [no test files]
ok      github.com/gravitational/gravity/lib/transfer   2.704s  coverage: 56.6% of statements
?       github.com/gravitational/gravity/lib/update     [no test files]
ok      github.com/gravitational/gravity/lib/update/cluster     2.204s  coverage: 32.3% of statements
?       github.com/gravitational/gravity/lib/update/cluster/checks      [no test files]
ok      github.com/gravitational/gravity/lib/update/cluster/phases      2.077s  coverage: 12.6% of statements
ok      github.com/gravitational/gravity/lib/update/clusterconfig       1.939s  coverage: 46.3% of statements
?       github.com/gravitational/gravity/lib/update/clusterconfig/phases        [no test files]
ok      github.com/gravitational/gravity/lib/update/environ     1.971s  coverage: 33.3% of statements
?       github.com/gravitational/gravity/lib/update/environ/phases      [no test files]
?       github.com/gravitational/gravity/lib/update/internal/rollingupdate      [no test files]
?       github.com/gravitational/gravity/lib/update/internal/rollingupdate/phases       [no test files]
?       github.com/gravitational/gravity/lib/update/system      [no test files]
?       github.com/gravitational/gravity/lib/users      [no test files]
?       github.com/gravitational/gravity/lib/users/suite        [no test files]
ok      github.com/gravitational/gravity/lib/users/usersservice 17.199s coverage: 40.8% of statements
ok      github.com/gravitational/gravity/lib/utils      3.647s  coverage: 23.5% of statements
ok      github.com/gravitational/gravity/lib/utils/cli  1.389s  coverage: 95.2% of statements
ok      github.com/gravitational/gravity/lib/utils/helm 1.183s  coverage: 55.1% of statements
?       github.com/gravitational/gravity/lib/utils/kubectl      [no test files]
?       github.com/gravitational/gravity/lib/vacuum     [no test files]
ok      github.com/gravitational/gravity/lib/vacuum/internal/fsm        1.569s  coverage: 41.1% of statements
?       github.com/gravitational/gravity/lib/vacuum/internal/phases     [no test files]
?       github.com/gravitational/gravity/lib/vacuum/prune       [no test files]
?       github.com/gravitational/gravity/lib/vacuum/prune/journal       [no test files]
ok      github.com/gravitational/gravity/lib/vacuum/prune/pack  1.660s  coverage: 79.6% of statements
?       github.com/gravitational/gravity/lib/vacuum/prune/registry      [no test files]
ok      github.com/gravitational/gravity/lib/validate   1.703s  coverage: 34.7% of statements
?       github.com/gravitational/gravity/lib/webapi     [no test files]
?       github.com/gravitational/gravity/lib/webapi/ui  [no test files]
?       github.com/gravitational/gravity/tool/common    [no test files]
?       github.com/gravitational/gravity/tool/gravity   [no test files]
?       github.com/gravitational/gravity/tool/gravity/cli       [no test files]
?       github.com/gravitational/gravity/tool/tele      [no test files]
?       github.com/gravitational/gravity/tool/tele/cli  [no test files]
?       github.com/gravitational/gravity/tool/terraform-provider-gravity        [no test files]
make: Leaving directory '/gopath/src/github.com/gravitational/gravity/build.assets'
make[1]: Leaving directory '/home/walt/git/gravity/build.assets'
```
</details>

### CODE REVIEW

**Comment by wadells** [comment]
The test config diff:

```
walt@work:~/git/gravity$ diff pr.before pr.after                                                                 
5,6c5,9
< upgrade={"flavor":"three","nodes":3,"role":"node","service_uid":997,"service_gid":994,"os":"ubuntu:16","storage_driver":"overlay2","from":"/telekube_6.1.18.tar"}
< upgrade={"flavor":"three","nodes":3,"role":"node","service_uid":997,"service_gid":994,"os":"ubuntu:16","storage_driver":"overlay2","from":"/telekube_6.3.6.tar"}
---
> upgrade={"flavor":"three","nodes":3,"role":"node","os":"centos:7","from":"/telekube_6.1.0.tar","service_uid":997,"service_gid":994,"storage_driver":"overlay2"}
> upgrade={"flavor":"three","nodes":3,"role":"node","os":"debian:9","from":"/telekube_6.2.5.tar","service_uid":997,"service_gid":994,"storage_driver":"overlay2"}
> upgrade={"flavor":"three","nodes":3,"role":"node","os":"redhat:7","from":"/telekube_6.1.31.tar","service_uid":997,"service_gid":994,"storage_driver":"overlay2"}
> upgrade={"flavor":"three","nodes":3,"role":"node","os":"redhat:7","from":"/telekube_6.2.0.tar","service_uid":997,"service_gid":994,"storage_driver":"overlay2"}
> upgrade={"flavor":"three","nodes":3,"role":"node","os":"ubuntu:18","from":"/telekube_6.3.18.tar","service_uid":997,"service_gid":994,"storage_driver":"overlay2"}
```

**Comment by knisbet** [comment]
Sorry, why is this going into the 6.3 branch?

**Comment by wadells** [comment]
> Sorry, why is this going into the 6.3 branch?

Because @a-palchikov and I got burned before by not backporting robotest compatibility to 6.3 after it was End of Support.

https://github.com/gravitational/gravity/pull/1507 occurred a month after EoS (there is an RCA in the team drive).  Ever since then I've been extra cautious about backporting branch agnostic work to 6.3, just in case.

I'd be thrilled to wash my hands of 6.3 if we're actually done with it.

**Comment by wadells** [comment]
Also -- being careful to not fall for sunk cost fallacy:

I've paid the development price for these ports & the PR build shows they're working. At worst, merging them is superfluous because there is never another 6.3 pr/release.  At best, if we do need to do another 6.3 fix, having these will save the next dev time (if only because of the test etcd cert port).

**Comment by wadells** [comment]
After an in-person discussion with @r0mant, we've decided another 6.3 release is unlikely.  The only known user of this branch is moving to 7.0.

**Pull request closed without merging**
