### PR TITLE
Kevin/master/1689 ensure resumption on upgrade leader

### PR DESCRIPTION
**Pull request by knisbet**
## Description

Forces resumed upgrades that contain etcd upgrade phases to be run on the node coordinating the upgrades. This prevents unsynced plan phases from blocking the upgrade due to dependency resolution failures.

## Type of change

* Bug fix (non-breaking change which fixes an issue)
* This change has a user-facing impact

## Linked tickets and other PRs

* Closes #, refs #
https://github.com/gravitational/gravity/issues/1689

## TODOs

- [x] Self-review the change
- [ ] Write tests
- [x] Perform manual testing
- [ ] Address review feedback

## Testing done

Do a manual upgrade that contains an etcd upgrade, and then resume from a different node.

Node 1:
```
root@kevin-test1:~/build# ./upload
Thu Jun 18 20:12:20 UTC	Importing application telekube v7.1.0-alpha.1.91
Thu Jun 18 20:13:15 UTC	Synchronizing application with Docker registry 10.162.0.7:5000
Thu Jun 18 20:15:07 UTC	Synchronizing application with Docker registry 10.162.0.6:5000
Thu Jun 18 20:16:18 UTC	Application has been uploaded
root@kevin-test1:~/build# ./gravity upgrade --manual
Thu Jun 18 20:16:38 UTC	Upgrading cluster from 7.0.0 to 7.1.0-alpha.1.91
Thu Jun 18 20:16:39 UTC	Deploying agents on cluster nodes
Deployed agent on kevin-test2 (10.162.0.6)
Deployed agent on kevin-test1 (10.162.0.7)
The operation has been created in manual mode.

See https://gravitational.com/gravity/docs/cluster/#managing-an-ongoing-operation for details on working with operation plan.
```

Node 2:
```
root@kevin-test2:~/7.0.0# /var/lib/gravity/site/update/agent/gravity plan resume
[ERROR]: Plan must be resumed on node Server(AdvertiseIP=10.162.0.7, Hostname=kevin-test1, Role=node, ClusterRole=master)
```

### CODE REVIEW

**Review by r0mant — COMMENTED** [review]
I'm curious what would be the downsides of just enforcing resume to launch from coordinator in all cases, not just when etcd is present. The behavior would be more consistent.

Also, this probably needs a support for a `--force` flag to override this check.

**Review by r0mant — COMMENTED** [review]
Also, this particular fix doesn't really address the actual issue the upgrade failed in the first place, right? From the investigation it looked like the original reason upgrade failed is "etcd restore" phase was executed on "node1" while "node3" was coordinating the upgrade. But this particular fix only ensures that the manual "resume" command is run from coordinator, not that "restore" phase would be run on the correct node. Or am I missing something?

I think we need to add appropriate `ExecServer` to all etcd phases to make sure they're executed where they should be. From the plan it's visible they're missing exec servers right now.

**Comment by knisbet** [comment]
> I'm curious what would be the downsides of just enforcing resume to launch from coordinator in all cases, not just when etcd is present. The behavior would be more consistent.
> 
> Also, this probably needs a support for a `--force` flag to override this check.

The reason of the narrow approach, is that it was the original design intent of the upgrade process to be resumable from any node, and the restrictions placed on the etcd upgrades when originally implemented were these violations should only occur during etcd phases. So I'm just continuing with the restrictions that were placed on me from when etcd upgrades were originally implemented.

**Comment by knisbet** [comment]
> Also, this particular fix doesn't really address the actual issue the upgrade failed in the first place, right? From the investigation it looked like the original reason upgrade failed is "etcd restore" phase was executed on "node1" while "node3" was coordinating the upgrade. But this particular fix only ensures that the manual "resume" command is run from coordinator, not that "restore" phase would be run on the correct node. Or am I missing something?
> 
> I think we need to add appropriate `ExecServer` to all etcd phases to make sure they're executed where they should be. From the plan it's visible they're missing exec servers right now.

It does address the problem. The issue is, that node 1 was coordinating the upgrade, but failed on some endpoints step. The upgrade was then resumed on node 3 within a user shell, which meant node 3 was now effectively coordinating the upgrade, because the resume was allowed to run on node 3. This changes the resume to be run on the same node that started the upgrade, which would be node 1 in our failure scenario.

**Review by r0mant — APPROVED** [review]
Don't forget to backport to 5.5 pls.

**Pull request merged**
