### PR TITLE
Bump logging application

### PR DESCRIPTION
**Pull request by UnderGreen**
## Description

* Run containers with normal user [#81](https://github.com/gravitational/logging-app/pull/81)
* Fix panic in parseCSVIntoMap [#79](https://github.com/gravitational/logging-app/pull/79)

## Type of change

* Breaking change (fix or feature that would cause existing functionality to not work as expected)
* This change has a user-facing impact

## TODOs

- [x] Self-review the change
- [x] Perform manual testing
- [ ] Update documentation about persistence problem

### CODE REVIEW

**Comment by UnderGreen** [comment]
@wadells Can you please reschedule ci tests again? I realized I didn't push the logging app tag after making it locally.

**Comment by wadells** [comment]
> @wadells Can you please reschedule ci tests again? I realized I didn't push the logging app tag after making it locally.

Done.

Sorry for the delay, I was out on Friday.

**Comment by wadells** [comment]
> Breaking change (fix or feature that would cause existing functionality to not work as expected)

Can you add what the breaking change is to the PR description?  This will help (probably me) write release notes.

**Review by wadells — APPROVED** [review]

**Comment by UnderGreen** [comment]
As we discussed in upstream PR for logging application with the upgrade to that version we are going to lose all logging data, which I consider as a breaking change(but maybe it is not).

**Pull request merged**
