### PR TITLE
Remove outdated instance documentation.

### PR DESCRIPTION
**Pull request by wadells**
This content isn't presently helping us, and newer mkdocs complain
that it contains invalid links:
```
WARNING -  Documentation file 'instance.md' contains a link to 'images/hc.png' which is not found in the documentation files.
WARNING -  Documentation file 'instance.md' contains a link to '../deploy/wake.gravitational.io' which is not found in the documentation files.
```

I double checked that no other files were using these images:

```
walt@work:~/git/gravity$ cat images | xargs -n1 -i{} ack --nogroup {} docs   
docs/4.x/instance.md:9:![deploy](images/instance.png)
docs/5.x/instance.md:9:![deploy](images/instance.png)
docs/6.x/instance.md:9:![deploy](images/instance.png)
docs/4.x/instance.md:14:![deploy](images/instance4.png)
docs/5.x/instance.md:14:![deploy](images/instance4.png)
docs/6.x/instance.md:14:![deploy](images/instance4.png)
docs/4.x/instance.md:18:![deploy](images/instance3.png)
docs/5.x/instance.md:18:![deploy](images/instance3.png)
docs/6.x/instance.md:18:![deploy](images/instance3.png)
docs/4.x/instance.md:22:![deploy](images/lb.png)
docs/5.x/instance.md:22:![deploy](images/lb.png)
docs/6.x/instance.md:22:![deploy](images/lb.png)
docs/4.x/instance.md:23:![deploy](images/lb-groups.png)
docs/5.x/instance.md:23:![deploy](images/lb-groups.png)
docs/6.x/instance.md:23:![deploy](images/lb-groups.png)
docs/4.x/instance.md:24:![deploy](images/hc.png)
docs/5.x/instance.md:24:![deploy](images/hc.png)
docs/6.x/instance.md:24:![deploy](images/hc.png)
docs/4.x/instance.md:25:![deploy](images/lb-wake.png)
docs/5.x/instance.md:25:![deploy](images/lb-wake.png)
docs/6.x/instance.md:25:![deploy](images/lb-wake.png)
docs/4.x/instance.md:26:![deploy](images/lb-dns.png)
docs/5.x/instance.md:26:![deploy](images/lb-dns.png)
docs/6.x/instance.md:26:![deploy](images/lb-dns.png)
docs/4.x/instance.md:27:![deploy](images/lb-idle.png)
docs/5.x/instance.md:27:![deploy](images/lb-idle.png)
docs/6.x/instance.md:27:![deploy](images/lb-idle.png)
docs/4.x/instance.md:31:![deploy](images/volume.png)
docs/5.x/instance.md:31:![deploy](images/volume.png)
docs/6.x/instance.md:31:![deploy](images/volume.png)
docs/4.x/instance.md:35:![deploy](images/dns.png)
docs/5.x/instance.md:35:![deploy](images/dns.png)
docs/6.x/instance.md:35:![deploy](images/dns.png)
docs/4.x/instance.md:123:![deploy](images/oidc.png)
docs/5.x/instance.md:123:![deploy](images/oidc.png)
docs/6.x/instance.md:123:![deploy](images/oidc.png)
docs/4.x/instance.md:130:![deploy](images/deploy.png)
docs/5.x/instance.md:130:![deploy](images/deploy.png)
docs/6.x/instance.md:130:![deploy](images/deploy.png)
```

### CODE REVIEW

**Comment by wadells** [comment]
@klizhentas You added this content in https://github.com/gravitational/gravity.e/commit/6d95afe7a0122ebf2c5fb9d97b95f5e6847ed8ea, so your opinion is probably the most relevant as to whether it is safe to remove.

**Review by knisbet — APPROVED** [review]
The markdown files are certainly outdated and internal references from when the code was private. So it's safe to remove.

**Review by a-palchikov — APPROVED** [review]

**Comment by wadells** [comment]
This PR is hitting https://github.com/gravitational/robotest/issues/154 preventing the CI from even running. I should have anticipated this, given the last time I made a PR from my fork (a couple months back) I filed the issue.

The short of it is, I either need to:

1) re-issue this PR from a ref inside gravitational/gravity (instead of from wadells/gravity) OR
2) fix https://github.com/gravitational/robotest/issues/154.  I'm inclined towards this route, since this bug will hit literally every external contributor

**Comment by wadells** [comment]
Closing until I get PR builds from forks figured out.  Hoping to revisit that next week.

**Pull request closed without merging**
