### PR TITLE
[7.0.x] Bump monitoring version to 7.0.9

### PR DESCRIPTION
**Pull request by UnderGreen**
## Description

* Fix for the node-exporter collector [#208](https://github.com/gravitational/monitoring-app/pull/208)

## Type of change

* Bug fix (non-breaking change which fixes an issue)

## Linked tickets and other PRs

* Refs [#208](https://github.com/gravitational/monitoring-app/pull/208)

## TODOs

- [x] Self-review the change
- [x] Perform manual testing
- [ ] Address review feedback

### CODE REVIEW

**Review by bernardjkim — APPROVED** [review]

**Comment by UnderGreen** [comment]
Any insights why jenkins check errored?

**Comment by wadells** [comment]
> Any insights why jenkins check errored?

Something is up with Robotest + RHEL -- doesn't look related to your change.  I'm researching currently and will get back to you once I have a diagnosis/fix.

**Review by wadells — APPROVED** [review]
Picking up https://github.com/gravitational/gravity/pull/2455 (hopefully merged early tomorrow) should fix the jenkins failure.

**Comment by UnderGreen** [comment]
@wadells do you know why it is still failing?

**Comment by wadells** [comment]
> @wadells do you know why it is still failing?

I haven't done a full investigation, but it is upgrade scenarios that are failing -- not a single upgrade ran to completion. For example:

```
"{"role":"node","cluster":"","flavor":"three","remote_support":false,"state_dir":"/var/lib/gravity","os":{"Vendor":"redhat","Version":"7.9"},"storage_driver":"overlay2","installer_url":"/images/robotest-7.0.31-dev.9.tar","service_uid":997,"service_gid":994,"nodes":3,"script":null,"from":"/images/robotest-6.1.48.tar","gravity_url":"/robotest-bin/gravity"}"
```

Shows that the upgrade is running the `monitoring-app` phase for > 10 minutes before eventually failing (timing out?)

I'd recommend trying to run an upgrade and see if you can repro.  Unfortunately, robotest is currently hardcoded to kubeadm, so I don't know that you'll even be able to use it to repro without cleaning up.

**Pull request merged**
