### PR TITLE
Adding short format to tele ls

### LINKED ISSUE #1816: [BUG] `tele ls --format short` reports "[ERROR]: unknown output format "short", supported are: [text short json yaml]"
## Describe the bug
```
$ tele version
Edition:        enterprise
Version:        7.1.0-alpha.1.113
Git Commit:     39432eb08f243f101c11807923832e487e67fef3
Helm Version:   v2.15
$ tele ls --format short --hub=<redacted> --token=<redacted>
Displaying latest stable versions of application and cluster images in <redacted>. Use --all flag to show all.

[ERROR]: unknown output format "short", supported are: [text short json yaml]
$ tele ls --help
usage: tele ls [<flags>]

List cluster and application images published to Gravity Hub.

Flags:
      --help                 Show context-sensitive help (also try --help-long and --help-man).
      --debug                Enable debug mode.
      --insecure             Skip TLS verification when making HTTP requests.
      --state-dir=STATE-DIR  The build cache directory to speed up subsequent builds. Defaults to ~/.gravity.
      --hub=HUB              Address of the Gravity Hub to execute the command against. Defaults to the currently active cluster or the Gravitational distribution portal.
  -t, --token=TOKEN          Gravity authentication token.
      --format=text          Output format: [text short json yaml].
      --all                  Display all available versions.
```

## Expected behavior
I expect the --help documentation and error message to match the behavior.  Short should be removed as an format option, or work properly when provided.

## Environment (please complete the following information):
 - OS [e.g. Redhat 7.4]: Ubuntu 20.04
 - Gravity [e.g. 5.5.4]: 7.1.0-alpha.1, master
 - Platform [e.g. Vmware, AWS]: desktop

## Additional Info
`--format short` isn't anywhere in the online documentation

### PR DESCRIPTION
**Pull request by zeelewis**
## Description

Adds missing short format output to `tele ls` to coincide with the tele help description.

## Type of change

* Bug fix (non-breaking change which fixes an issue)

## Linked tickets and other PRs

* Closes #1816 

## TODOs

- [ ] Self-review the change
- [ ] Write tests
- [ ] Perform manual testing
- [ ] Write documentation
- [ ] Address review feedback
- [ ] Update upstream references / tags / versions after upstream PR merges (linked above)

## Implementation

Outputs a single column list of images without header.
Ex:
```
# ./build/tele ls --format=short --all | head
Displaying all available application and cluster images in hub.gravitational.io.

gravity:7.1.0-alpha.5
gravity:7.0.30
gravity:7.0.29
gravity:7.0.28
```

## Testing done

Built and tested `tele ls --format=short`

### CODE REVIEW

**Review by wadells — APPROVED** [review]
Thanks for your contribution @zeelewis! LGTM.

No need to worry about the jenkins failure -- it doesn't work with PRs from outside contributors.

**Review by bernardjkim — APPROVED** [review]

**Comment by wadells** [comment]
@zeelewis I've fixed CI with external PRs, but it looks like the recently added golint is failing on this patch, as seen at:

https://drone.teleport.dev/gravitational/gravity/222/1/6

```
lib/catalog/lister.go:248: File is not `gofmt`-ed (gofmt)
```

Would you give `make lint` a run and fix the issues?  Or if you're not interested in carrying this forward, let me know.

**Comment by zeelewis** [comment]
@wadells thanks. I've updated the branch after running it through gofmt. It was complaining that I used spaces instead of tabs.

**Comment by wadells** [comment]
Thanks for your contribution!

**Pull request merged**
