### PR TITLE
[7.0.x] Fix sortorder dep

### PR DESCRIPTION
**Pull request by bernardjkim**
## Description

The vbom.ml domain was taken down and this broke the `vbom.ml/util/sortorder` dependency: https://github.com/fvbommel/util/issues/6. This PR adds a temporary workaround by replacing the import paths from `vbom.ml/util/sortorder` -> `github.com/fvbommel/sortorder`.

## Usage
- `make fix-sortorder` should be run after updating dependencies. This will update the import paths.
- `make dep-ensure` combines `dep ensure` and `fix-sortorder` target.

## Type of change

* Bug fix (non-breaking change which fixes an issue)
* Internal change (not necessarily a bug fix or a new feature)

## Linked tickets and other PRs

* Refs https://github.com/fvbommel/util/issues/6

## Additional information
When attempting to update dependencies using `dep`, the update fails with the follow issue:
```
$ dep ensure
Solving failure: unable to deduce repository and source type for "vbom.ml/util": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://vbom.ml/util?go-get=1": Get http://vbom.ml/util?go-get=1: dial tcp: lookup vbom.ml on 127.0.0.53:53: no such host
```

### CODE REVIEW

**Review by r0mant — COMMENTED** [review]
How should this target be used when updating dependencies?

**Comment by a-palchikov** [comment]
How does it affect version/7.0.x? All I saw were issues with `go mod` which is not used in 7.x.
As a side note, would it be possible to workaround this with making `vbom.ml/util/sortorder` an explicit dependency (i.e. list in Gopkg.toml) and create an alias to the new location?

**Comment by bernardjkim** [comment]
@a-palchikov 
I've tried making `vbom.ml/util/sortorder` an explicit dependency and specifying a `source`, but it didn't seem to fix the issue. Not sure if I implemented it correctly or if there is a different way to create an alias, but this is what I tried.
```
[[override]]
  name = "vbom.ml/util/sortorder"
  source = "github.com/fvbommel/sortorder"
  version = "v1.0.1"
```
```
$ dep ensure
The following issues were found in Gopkg.toml:

  ✗ unable to deduce repository and source type for "vbom.ml/util/sortorder": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://vbom.ml/util/sortorder?go-get=1": Get http://vbom.ml/util/sortorder?go-get=1: dial tcp: lookup vbom.ml on 127.0.0.53:53: no such host

ProjectRoot name validation failed
```

**Comment by a-palchikov** [comment]
Ok, it looks like it's an [old issue](https://github.com/golang/dep/issues/1169) with dep.

**Comment by bernardjkim** [comment]
@r0mant, @a-palchikov 
Added some additional information on issue with 7.0.x, and added a usage section in the original comment for information on make target usages. Use target `make dep-ensure` will update the dependencies and also fix sortorder import paths.

**Review by a-palchikov — APPROVED** [review]

**Pull request merged**
