### PR TITLE
Add RHEL 8.2 and CentOS 8.2 to Gravity 5.5's supported distros

### PR DESCRIPTION
**Pull request by wadells**
## Description
Add RHEL 8.2 and CentOS 8.2 to Gravity 5.5's supported distros.

## Type of change
* Documentation
* This change has a user-facing impact

## TODOs
- [x] Self-review the change
- [x] Perform manual testing
- [x] Address review feedback

## Testing done
Redhat 8.2 3 node install: [logs](https://console.cloud.google.com/logs/query;query=severity%3E%3DINFO%0Alabels.__uuid__%3D%22c5bb7a8a-40e2-449b-9d3e-9f6b945a86d3%22%0Alabels.__suite__%3D%227d8f04bb-30e5-4f4f-9273-ab372c275b34%22;timeRange=2020-10-07T17:27:45Z%2F2020-10-07T18:27:45Z?project=kubeadm-167321)

CentOS 8.2 3 node install: [logs](https://console.cloud.google.com/logs/query;query=severity%3E%3DINFO%0Alabels.__uuid__%3D%22ea69fe80-350c-445a-bfce-854ddb2b2615%22%0Alabels.__suite__%3D%2216db9334-6727-4aa9-b29d-ca62ca15e61c%22;timeRange=2020-10-07T17:46:14Z%2F2020-10-07T18:46:14Z?project=kubeadm-167321)

### CODE REVIEW

**Review by r0mant — APPROVED** [review]
Thanks @wadells!

**Review by a-palchikov — APPROVED** [review]

**Comment by a-palchikov** [comment]
I've been thinking about this in the context of the issues I've run into recently with 7.0.x on CentOS 8 with SELinux in enforcing mode and it does not seem to work for 5.5.x exactly on the same grounds - the upgrade workflow will fail to set up an agent service since systemd requires additional permissions to be able to execute files in `/var/lib/...`.
So we might either want to mention this or implement SELinux support/fix for this workflow.

**Comment by wadells** [comment]
> I've been thinking about this in the context of the issues I've run into recently with 7.0.x on CentOS 8 with SELinux in enforcing mode and it does not seem to work for 5.5.x exactly on the same grounds - the upgrade workflow will fail to set up an agent service since systemd requires additional permissions to be able to execute files in `/var/lib/...`.
> So we might either want to mention this or implement SELinux support/fix for this workflow.

If I understand correctly, you're saying a 5.5.x install will work with SELinux enforcing, but upgrading away from 5.5.x will fail?

**Comment by a-palchikov** [comment]
Yes, the upgrades will fail.

**Pull request merged**
