### PR TITLE
Run gravity remove before instance is terminated in AWS

### PR DESCRIPTION
**Pull request by helgi**
AWS can take a while to terminate an instance, doing the remove first will trigger the shrink operation and let the cluster generally settle itself while AWS does its business. I have a feeling it will help resolve https://github.com/gravitational/gravity/issues/943 to some small extent

In internal asg roller I have doing `gravity remove` before AWS terminated (codified) has helped a lot with stability. When I had the roller only depend on the AWS lifecycle hook (this functionality) I would have `failed` nodes in `serf` frequently or other funky behaviours.

### CODE REVIEW

**Comment by helgi** [comment]
Understood that https://github.com/gravitational/gravity/pull/315 specifically made the code wait for instance termination before the shrink operation; I'm not sure of the contest but given my previous comment I think `remove` needs to happen first but then again I can't see the `e` ticket referenced :)

**Comment by knisbet** [comment]
Hmm, so I'm not sure if this will help with #943, and there are also some unknowns on other possible issues. My concern is, the removeInstance instance code starts a shrink operation, which will if the node is online start an uninstall process on the particular node using teleport. If the node goes offline mid-uninstall, it's hard for me to predict what side effects may occur. 

So to me the current ordering does make sense, where when we see the node is fully terminated, we launch the remove process (for removing a dead node) after the instance has terminated. Although it does beg the question, if we're waiting for the node to be terminated, I'm not sure our theory that the node still existing causing the node to rejoin the serf cluster is accurate. 

The other route to go is like we discussed a few weeks ago, is to launch removeInstance, but to properly heartbeat the AWS ASG termination event to keep the node alive while running the uninstall process on the node. Although I'm of the opinion that when terminating an AWS node we shouldn't need to rely on a clean uninstallation happening.

**Comment by helgi** [comment]
In a different code base doing the above what I do is I have a "wait until node is removed from gravity state" and then I run AWS terminate. In the gravity code as it is right now it basically does the inverse.

This might not be the serf issue but it would explain why I have seen gravity consider a node to be available but offline beyond it's AWS existance where a **worker** that was expanding would use **master** that was available but marked offline; I only saw that when I use the AWS lifecycle hook  to deal with the `gravity remove` aspect, as soon as I did the "gravity remove, wait until node is gone, do aws terminate" I stopped seeing **workers** attempt to connect to a non-existent **master**.

--- Above is just context against why this change made sense (knowing it's not fully baked) ---

The option we talked about a few weeks back would be more than sufficient I think, and I agree, a clean uninstall isn't a requirement as long as `gravity remove` (or similar) can cleanup all the internals properly. Is there any anything essential `uninstall` if the node is being fully destroyed?

I could imagine a new `phase` that would put a node (especially when it's a **master**) into a `pre-shrink ` of sorts mode, which in turn takes it out of any normal interaction with the cluster, i.e. new **workers** would not be told to use a node (**master**) in `pre-shrink` state and could even be instructed on the fly to restart it's `expand` against a new master if its current master is being put down.

**Comment by helgi** [comment]
https://github.com/gravitational/gravity/pull/1251 will resolve this much better

**Pull request closed without merging**
