### PR TITLE
(5.5) Refactor robotest configuration - keep upgrade_from releases current.

### PR DESCRIPTION
**Pull request by wadells**
## Description
Port robotest config refactoring from #1837 

This port introduces (or rather carries forward) some additions not in master (#1837), 7.0 (#1876), or 6.3 (#1877):

5.5 includes a list of custom 5.5 versions to test upgrade from as well as an "upgrade via" test.  Furthermore, I edited all the 5.5 specific tests from "ubuntu:16"  (previously used on 5.5.x) to "centos:7" as I believe this is closer to what we see commonly these versions running on in the field.

Speaking of OSes, this intrudes a significant number of new OSes we haven't been testing on in 5.5, where ubuntu:16 reigned king.  I double checked all these are supported by Gravity 5.5 (at least according to the docs) but I expect some may fail on the 5.2 or 5.0 front.  I'll sort through them in the PR results.

Lastly, gravity 5.5's incompatibility with Robotest 2.0 is negotiated -- this port sticks with the uid-gid tag and leaves out shrink testing. Still looking for priority to return to https://github.com/gravitational/robotest/issues/247.

## Type of change
* Internal change (not necessarily a bug fix or a new feature)

## Linked tickets and other PRs
* Ports #1837 

## TODOs
- [x] Self-review the change
- [x] Audit automated test run for correctness
- [ ] Address review feedback

## Testing done
See  #1837 for the original testing. For 5.5: the PR Jenkins run should sufficiently exercise the 5.5 PR build relevant changes. We don't care about testing the nightly changes because we don't run nighties on 5.5 so although I made an minor effort to keep this file branch relevant mistakes are moot.

### CODE REVIEW

**Review by r0mant — COMMENTED** [review]
Looks like robotest branch is failing with

```
04:18:06 [robotest] ./build.assets/robotest/utils.sh: line 22: 1: latest_regular_release_tag ref
04:18:06 [robotest] ./build.assets/robotest/pr_config.sh: line 20: UPGRADE_MAP[$(recommended_upgrade_tag $(branch 5.0.x))]: bad array subscript
04:18:06 [robotest] make[1]: *** [robotest-run-suite] Error 1
```

**Comment by wadells** [comment]
Fixes:
* Changed latest 5.0.x -> 5.0.36 because this repo doen't have 5.0 branch info
* Removed centos:8
* Split out `tele login` and used the `--ops` flag.

Here is the config diff:

```
walt@work:~/git/gravity$ diff pr.before pr.after                                                                                                                                              
2,13c2,13                                                                                                                                                                                     
< install={"installer_url":"/installer/opscenter.tar","nodes":1,"flavor":"standalone","role":"node","os":"ubuntu:16","ops_advertise_addr":"example.com:443"}                                  
< resize={"to":3,"flavor":"one","nodes":1,"role":"node","state_dir":"/var/lib/telekube","os":"ubuntu:16","storage_driver":"overlay2"}                                                         
< upgrade={"flavor":"three","nodes":3,"role":"node","service_uid":997,"service_gid":994,"os":"ubuntu:16","storage_driver":"overlay2","from":"/telekube_5.0.35.tar"}                           
< upgrade={"flavor":"three","nodes":3,"role":"node","service_uid":997,"service_gid":994,"os":"ubuntu:16","storage_driver":"overlay2","from":"/telekube_5.2.0.tar"}                            
< upgrade={"flavor":"three","nodes":3,"role":"node","service_uid":997,"service_gid":994,"os":"ubuntu:16","storage_driver":"overlay2","from":"/telekube_5.2.16.tar"}
< upgrade={"flavor":"three","nodes":3,"role":"node","service_uid":997,"service_gid":994,"os":"ubuntu:16","storage_driver":"overlay2","from":"/telekube_5.5.0.tar"}
< upgrade={"flavor":"three","nodes":3,"role":"node","service_uid":997,"service_gid":994,"os":"ubuntu:16","storage_driver":"overlay2","from":"/telekube_5.5.28.tar"}
< upgrade={"flavor":"three","nodes":3,"role":"node","service_uid":997,"service_gid":994,"os":"ubuntu:16","storage_driver":"overlay2","from":"/telekube_5.5.36.tar"}
< upgrade={"flavor":"three","nodes":3,"role":"node","service_uid":997,"service_gid":994,"os":"ubuntu:16","storage_driver":"overlay2","from":"/telekube_5.5.37.tar"}
< upgrade={"flavor":"three","nodes":3,"role":"node","service_uid":997,"service_gid":994,"os":"ubuntu:16","storage_driver":"overlay2","from":"/telekube_5.5.38.tar"}
< upgrade={"flavor":"three","nodes":3,"role":"node","service_uid":997,"service_gid":994,"os":"ubuntu:16","storage_driver":"overlay2","from":"/telekube_5.5.40.tar"}
< upgrade={"flavor":"three","nodes":3,"role":"node","service_uid":997,"service_gid":994,"os":"ubuntu:16","storage_driver":"overlay2","from":"/telekube_5.5.41.tar"}
---
> install={"installer_url":"/installer/opscenter.tar","nodes":1,"flavor":"standalone","role":"node","os":"ubuntu:18","ops_advertise_addr":"example.com:443"}
> resize={"to":3,"flavor":"one","nodes":1,"role":"node","state_dir":"/var/lib/telekube","os":"ubuntu:18","storage_driver":"overlay2"}
> upgrade={"flavor":"three","nodes":3,"role":"node","os":"centos:7","from":"/telekube_5.0.36.tar","service_uid":997,"service_gid":994,"storage_driver":"overlay2"}
> upgrade={"flavor":"three","nodes":3,"role":"node","os":"centos:7","from":"/telekube_5.2.0.tar","service_uid":997,"service_gid":994,"storage_driver":"overlay2"}
> upgrade={"flavor":"three","nodes":3,"role":"node","os":"centos:7","from":"/telekube_5.5.28.tar","service_uid":997,"service_gid":994,"storage_driver":"overlay2"}
> upgrade={"flavor":"three","nodes":3,"role":"node","os":"centos:7","from":"/telekube_5.5.36.tar","service_uid":997,"service_gid":994,"storage_driver":"overlay2"}
> upgrade={"flavor":"three","nodes":3,"role":"node","os":"centos:7","from":"/telekube_5.5.38.tar","service_uid":997,"service_gid":994,"storage_driver":"overlay2"}
> upgrade={"flavor":"three","nodes":3,"role":"node","os":"centos:7","from":"/telekube_5.5.40.tar","service_uid":997,"service_gid":994,"storage_driver":"overlay2"}
> upgrade={"flavor":"three","nodes":3,"role":"node","os":"centos:7","from":"/telekube_5.5.41.tar","service_uid":997,"service_gid":994,"storage_driver":"overlay2"}
> upgrade={"flavor":"three","nodes":3,"role":"node","os":"redhat:7","from":"/telekube_5.2.17.tar","service_uid":997,"service_gid":994,"storage_driver":"overlay2"}
> upgrade={"flavor":"three","nodes":3,"role":"node","os":"ubuntu:16","from":"/telekube_5.5.0.tar","service_uid":997,"service_gid":994,"storage_driver":"overlay2"}
> upgrade={"flavor":"three","nodes":3,"role":"node","os":"ubuntu:18","from":"/telekube_5.5.49.tar","service_uid":997,"service_gid":994,"storage_driver":"overlay2"}
```

**Review by a-palchikov — APPROVED** [review]
same typos as https://github.com/gravitational/gravity/pull/1878#discussion_r458327136

**Comment by wadells** [comment]
> same typos as [#1878 (comment)](https://github.com/gravitational/gravity/pull/1878#discussion_r458327136)

Fixed in c7256fc.

**Pull request merged**
